name: Build CL

on:
  workflow_dispatch:

#!/bin/bash
jobs:
  build-x86:
    env:
      BUILD_PLATFORM: "x86"
      BUILD_CONFIGURATION: Release
      OPENSSL_BUILD_PLATFORM: VC-WIN32
      ARCH: win32
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{env.ARCH}}
      - name: Build
        run: |
            curl -O https://www.lua.org/ftp/lua-5.2.4.tar.gz

            tar -xzf lua-5.2.4.tar.gz

            cd lua-5.2.4
            md bin
            md lib
            md include
            cp src/*.h include/
            cd src

            mv luac.c ..

            cl /nologo /D_CRT_SECURE_NO_WARNINGS /W3 /sdl /O2 /Oi /Oy- /D _WINDLL /MD /GS /fp:precise /Zc:inline /DNDEBUG *.c /link /out:../bin/lua.exe

            mv lua.c ..
            del lua.obj

            cl /nologo /D_CRT_SECURE_NO_WARNINGS /W3 /sdl /O2 /Oi /Oy- /D _WINDLL /MD /GS /fp:precise /Zc:inline /DNDEBUG /DLUA_BUILD_AS_DLL *.c /link /DLL /out:../bin/lua52.dll

            dir *.obj
            lib *.obj /out:../lib/lua52.lib
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: lua
          path: |
            lua-5.2.4/bin/*
            lua-5.2.4/lib/*
            lua-5.2.4/include/*
          if-no-files-found: error
