name: Build CL

on:
  workflow_dispatch:

jobs:
  build:
    env:
      LUA52_VERSION: "5.2.4"
      LUA53_VERSION: "5.3.6"
      LUA54_VERSION: "5.4.7"

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
        arch:
          - win32
          - win64

    steps:
      - name: Checkout Code  # this is required to use action.yaml via relative path
        uses: actions/checkout@v4

      - name: Show Files
        run: |
          dir

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - id: build52
        uses: ./
        with:
          name: "lua52"
          version: "${{ env.LUA52_VERSION }}"
      - name: Store Lua ${{ env.LUA52_VERSION }}
        uses: actions/upload-artifact@v4
        with:
          name: lua52-${{ matrix.arch }}
          path: |
            ${{ steps.build52.outputs.path }}/bin/*
            ${{ steps.build52.outputs.path }}/lib/*
            ${{ steps.build52.outputs.path }}/include/*
          if-no-files-found: error

      - id: build53
        uses: ./
        with:
          name: "lua53"
          version: "${{ env.LUA53_VERSION }}"
      - name: Store Lua ${{ env.LUA53_VERSION }}
        uses: actions/upload-artifact@v4
        with:
          name: lua53-${{ matrix.arch }}
          path: |
            ${{ steps.build53.outputs.path }}/bin/*
            ${{ steps.build53.outputs.path }}/lib/*
            ${{ steps.build53.outputs.path }}/include/*
          if-no-files-found: error

      - id: build54
        uses: ./
        with:
          name: "lua54"
          version: "${{ env.LUA54_VERSION }}"
      - name: Store Lua ${{ env.LUA54_VERSION }}
        uses: actions/upload-artifact@v4
        with:
          name: lua54-${{ matrix.arch }}
          path: |
            ${{ steps.build54.outputs.path }}/bin/*
            ${{ steps.build54.outputs.path }}/lib/*
            ${{ steps.build54.outputs.path }}/include/*
          if-no-files-found: error
